apiVersion: v1
kind: Pod
metadata:
  name: vault-test
  labels:
    app: vault-test
  annotations:
    # reference: https://github.com/banzaicloud/bank-vaults/tree/master/charts/vault-secrets-webhook
    vault.security.banzaicloud.io/vault-path: "httpbin"
    vault.security.banzaicloud.io/vault-role: "httpbin"
    vault.security.banzaicloud.io/vault-skip-verify: "true"
spec:
  serviceAccountName: default
  containers:
  - name: vault
    image: busybox
    command: ["sh", "-c", "echo $FOO $BAR && echo going to sleep... && sleep 1000"]
    env:
    - name: FOO
      value: "vault:demo/data/httpbin#foo"
    - name: BAR
      value: "vault:demo/data/httpbin#bar"